---
title: "titanic project"
author: "gani"
date: "23/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data loading}
train_titanic <- read.csv("C:/Users/ganesh/Documents/R files/DT/Titanic_train.csv",na.strings=c("","","NA"))
test_titanic  <- read.csv("C:/Users/ganesh/Documents/R files/DT/Titanic_train.csv",na.strings=c("","","NA"))
dim(train_titanic)
dim(test_titanic)
```

```{r data processing}

colSums(is.na(train_titanic))
colSums(is.na(test_titanic))

library(dplyr)
combined_titanic <- bind_rows(train_titanic,test_titanic)
dim(combined_titanic)
colSums(is.na(combined_titanic))
 
#passengerID, cabin, ticket

combined_titanic$Name        <- NULL
combined_titanic$PassengerId <-NULL
combined_titanic$Cabin       <-NULL
combined_titanic$Ticket      <-NULL

colSums(is.na(combined_titanic))

combined_titanic$Age[is.na(combined_titanic$Age)]   <- median(combined_titanic$Age,  na.rm = T)
combined_titanic$Fare[is.na(combined_titanic$Fare)] <- median(combined_titanic$Fare, na.rm = T)

summary(combined_titanic$Embarked)
combined_titanic$Embarked <- as.factor(combined_titanic$Embarked) 
combined_titanic$Embarked[is.na(combined_titanic$Embarked)] <- "S"

str(combined_titanic)
vect_titanic <- c("Survived","Pclass","SibSp","Parch","Sex")
combined_titanic[,vect_titanic] <- lapply(combined_titanic[,vect_titanic],as.factor)
str(combined_titanic)

#splitting combined_titanic into test and train
train_titanic <- combined_titanic[1:891,]
test_titanic  <- combined_titanic[892:1309,]
```

```{r treemodel_partykit}

#install.packages("partykit")
library(partykit)

tree_model_ctree <- ctree(Survived~. ,data = train_titanic)
plot(tree_model_ctree,type="simple")
```

```{r treemodel_rpart}
#install.packages("rpart")
library(rpart)

#install.packages("rpart.plot")
library(rpart.plot)

tree_model_rpart <- rpart(Survived~.,data = train_titanic)
rpart.plot(tree_model_rpart)
tree_model_rpart
```


``` {r predict_value}

#TEST DATA
#for ctree:
predicted_survived = predict(tree_model_ctree, test_titanic)
head(predicted_survived)

#for rpart:
predicted_survived_rpart = predict(tree_model_rpart, test_titanic, type = 'class')
head(predicted_survived_rpart)

#we cannot check how accurate model is for test data coz test data doesn't have target variable 'Survived'

#TRAIN DATA
#for ctree:
predicted_survived_train = predict(tree_model_ctree, train_titanic)
head(predicted_survived_train)

#for rpart:
predicted_survived_rpart_train = predict(tree_model_rpart, train_titanic, type = 'class')
head(predicted_survived_rpart_train)

#comparision for between ctree and rpart for train data:

table(actual = train_titanic$Survived, predicted = predicted_survived_train)
table(actual = train_titanic$Survived, predicted = predicted_survived_rpart_train)
```


#insurance data
``` {r insurance rpart}
insurance = read.csv('C:/Users/ganesh/Documents/R files/DT/insurance.csv', na.strings = c("", "", 'NA'))

insurance$X = NULL
colSums(is.na(insurance))
insurance$age = as.factor(insurance$age)
insurance$children = as.factor(insurance$children)

insurance_train = insurance[1:800,]
insurance_test  = insurance[801:1199,]

insurance_rpart = rpart(charges~., data = insurance_train)
rpart.plot(insurance_rpart)

predicted_insurance_rpart_train = predict(insurance_rpart, insurance_train)
head(predicted_insurance_rpart_train)

#root mean square error
error  = insurance_train$charges - predicted_insurance_rpart_train
rmse   = sqrt(mean(error^2))
rmse # 4612.261

```


``` {r insurance linearmodel}
# lm # RMSE
# rpart # RMSE

insurance_data<-read.csv("C:/Users/ganesh/Documents/R files/DT/insurance.csv",stringsAsFactors = T)

boxplot(insurance_data$charges)
summary(insurance_data$charges)
IQR(insurance_data$charges)  #8544.899
UW <- 12954+1.5*(8544.899);UW # 25771.35
insurance$charges[insurance$charges > UW] <- UW

insurance$X<-NULL
insurance$children <- as.factor(insurance$children)

lm_insurance <- lm(charges~.,data = insurance)
summary(lm_insurance)

#rmse for lm:
predicted_charges_lm   <- predict(lm_insurance,insurance)
res                    <- insurance$charges - predicted_charges_lm
rmse_lm_insurance      <- sqrt(mean(res^2))
rmse_lm_insurance # 4361.621
```